# Generated by Django 5.2.1 on 2025-08-20 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CellMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signal_level", models.IntegerField(blank=True, null=True)),
                ("carrier", models.CharField(blank=True, max_length=100, null=True)),
                ("technology", models.CharField(blank=True, max_length=50, null=True)),
                ("tac", models.IntegerField(blank=True, null=True)),
                ("plmn_id", models.CharField(blank=True, max_length=20, null=True)),
                ("arfcn", models.IntegerField(blank=True, null=True)),
                ("rsrq", models.IntegerField(blank=True, null=True)),
                ("rsrp", models.IntegerField(blank=True, null=True)),
                ("rscp", models.IntegerField(blank=True, null=True)),
                ("ec_no", models.IntegerField(blank=True, null=True)),
                ("rx_lev", models.IntegerField(blank=True, null=True)),
                ("time", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cell_measurements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-time"],
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("throughput", models.BigIntegerField(blank=True, null=True)),
                ("ping", models.BigIntegerField(blank=True, null=True)),
                ("web", models.BigIntegerField(blank=True, null=True)),
                ("dns", models.BigIntegerField(blank=True, null=True)),
                ("sms", models.BigIntegerField(blank=True, null=True)),
                ("time", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_measurements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-time"],
            },
        ),
    ]
