# Generated by Django 5.2.1 on 2025-08-21 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
        ("user", "0002_device_customuser_user_type_alter_customuser_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cellmeasurement",
            name="user",
        ),
        migrations.RemoveField(
            model_name="testresult",
            name="user",
        ),
        migrations.AddField(
            model_name="cellmeasurement",
            name="deviceId",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.device",
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="deviceId",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.device",
            ),
        ),
    ]
