# Generated by Django 5.2.1 on 2025-08-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_remove_cellmeasurement_user_remove_testresult_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cellmeasurement",
            name="signal_level",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="dns",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="ping",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="sms",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="web",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
