# Generated by Django 5.2.1 on 2025-08-20 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("polling_interval", models.BigIntegerField(default=5)),
                ("measurement_interval", models.BigIntegerField(default=5)),
                ("server_sync_interval", models.BigIntegerField(default=15)),
                ("test_interval", models.BigIntegerField(default=30)),
                ("ping_url", models.URLField(default="https://google.com")),
                ("web_url", models.URLField(default="https://google.com")),
                (
                    "sms_phone_number",
                    models.CharField(default="+989107607278", max_length=20),
                ),
                ("throughput_included", models.BooleanField(default=True)),
                ("ping_included", models.BooleanField(default=True)),
                ("web_included", models.BooleanField(default=True)),
                ("dns_included", models.BooleanField(default=True)),
                ("sms_included", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
